spring:
  datasource:
    url: jdbc:mysql://database-1.cemnrurbjhph.us-east-1.rds.amazonaws.com:3306/msc
    username: admin
    password: lCRF44L5eYvEvtfDuU82
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

folder:
  input: H:\Chathu\backend\backend-workload-analysis\src\main\resources\workload
  output: H:\Chathu\backend\backend-workload-analysis\src\main\resources\output
