@startuml
hide circle
hide methods

folder "VM Consolidation" as BillingRoundSpecificationFolder #FFF2CC {
    class ExecutableData <<Aggregate Root>> #D5A6BD {
        vmAllocationPolicy : String
        vmSelectionPolicy : String
        parameter: String
        workload: String
        active: Boolean
    }

    class AnalysedData <<Value Object>> #B6D7A8 {
         vmAllocationPolicy : String
         vmSelectionPolicy : String
         parameter : String
         workload : String
         experimentName : String
         groupId : String
         numberOfHosts : int
         numberOfVms : int
         numberOfMigrations : int
         numberOfHostShutdowns : int
         totalSimulationTime : double
         energy : double
         sla : double
         slaTimePerActiveHost : double
         slaDegradationDueToMigration : double
         executedDate: LocalDateTime
    }

    ExecutableData -- ResultAnalysis
}

@enduml
